# Workflow [ no identation required for naming the workflow]
# Should have name

name: Hello

# on tells when the workflow done [Give indentation by tab key ]
on:
  workflow_dispatch:
# Job = tells what the workflow should do, there can be more than one jobs, hence we write jobs,
# Jobs is an object so needs indentation
# Should be inside workflow
jobs:
  # 1st job give identation
  say-hello:
    # create an ephemeral container with ubuntu running
    runs-on: ubuntu-latest
    # that ephermeral container willl have steps to execute, hence name those steps and use run: run has the command.
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"

# Steps
# Should be inside the job


# Actions
# Should be inside the Steps
